config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  Spree::Core::Engine.add_routes do
    namespace :admin, path: Spree.admin_path do
      resources :departments
      resources :job_descriptions

    end

    devise_scope :spree_user do
      get '/signup/user/company' => 'user_registrations#new_user_company', :as => :signup_user_company
      post '/signup/user/company' => 'user_registrations#create_user_company', :as => :registration_user_company
      get '/signup/user/personal' => 'user_registrations#new_user_personal', :as => :signup_user_personal
      post '/signup/user/personal' => 'user_registrations#create_user_personal', :as => :registration_user_personal
    end

    resources :categories
  end
end

app/models/spree/department.rb
class Spree::Department < ApplicationRecord
    has_many :user_references
    has_many :users, :through => :user_references
    has_many :vendors, :through => :user_references
end

app/controllers/spree/admin/departments_controller.rb
module Spree
  module Admin
    class DepartmentsController < ResourceController
    end
  end
end

app/helpers/spree/admin/department_helper.rb
module Spree::Admin::DepartmentHelper
end

app/views/spree/admin/departments/_form.html.slim
.row data-hook="admin_property_form" 
  .col-12.col-md-6
    = f.field_container :name, class: ['form-group'] do
      = f.label :name, Spree.t(:name)
      span.required *
      = f.text_field :name, class: 'form-control'
      = f.error_message_on :name  
    = f.field_container :description, class: ['form-group'] do
      = f.label :description, Spree.t(:description)
      span.required *
      = f.text_field :description, class: 'form-control'
      = f.error_message_on :description
    = f.field_container :activated, class: ['form-group'] do
      = f.label :activated do
        = f.check_box :activated
        = Spree.t(:activated)

app/views/spree/admin/departments/edit.html.slim
- content_for :page_title do
  | #{link_to Spree.t(:departments), admin_departments_url} #{@department.name}
= render partial: 'spree/admin/shared/error_messages', locals: { target: @department }
= form_for [:admin, @department] do |f|
  fieldset
    = render partial: 'form', locals: { f: f }
    = render partial: 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/departments/index.html.slim
- content_for :page_title do
  = Spree.t(:departments)
- if can? :create, Spree::Department
- content_for :page_actions do
  = button_link_to Spree.t(:new_department), new_object_url, class: "btn-success", icon: 'add', id: 'admin_new_department_link'
- if @departments.any?
  table.table
    thead
      tr data-hook="admin_departments_index_headers" 
        th= Spree.t(:department_id)
        th.actions
    tbody
      - @departments.each do |department|
        tr data-hook="admin_departments_index_rows" id=("#{spree_dom_id department}") 
          td= department.name
          td.actions.text-right
            | #{link_to_edit(department, no_text: true) if can? :edit, department} #{link_to_delete(department, no_text: true) if can? :destroy, department}
- else
  .alert.alert-warning
    | #{Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Department))} #{link_to(Spree.t(:add_one), new_object_url) if can? :create, Spree::Department}

app/views/spree/admin/departments/new.html.slim
= render partial: 'spree/admin/shared/error_messages', locals: { target: @department }
- content_for :page_title do
  | #{link_to Spree.t(:properties), admin_departments_url} #{Spree.t(:new_department)}
= form_for [:admin, @department] do |f|
  fieldset data-hook="new_department" 
    = render partial: 'form', locals: { f: f }
    .form-actions
      = render partial: 'spree/admin/shared/new_resource_links'